{"version":3,"sources":["helpers.spec.js"],"names":["t","throws","TypeError","ReferenceError","Error"],"mappings":";;;;AAAA;;;;AAEA;;;;;;;;;;;;;;;;;;;;;;AAGA,mBAAK,kEAAL,EAAyE,aAAK;AAC5EA,IAAEC,MAAF;AAAA,WAAS;AAAA,aAAM,2BAAaC,SAAb,CAAN;AAAA,KAAT;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,MAAwCA,SAAxC;AACAF,IAAEC,MAAF;AAAA,WAAS;AAAA,aAAM,2BAAaE,cAAb,CAAN;AAAA,KAAT;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,MAA6CA,cAA7C;AACAH,IAAEC,MAAF;AAAA,WAAS;AAAA,aAAM,2BAAaG,KAAb,CAAN;AAAA,KAAT;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,MAAoCA,KAApC;AACD,CAJD","file":"helpers.spec.js","sourcesContent":["import test from 'ava'\n\nimport { runtimeError } from '../../source/utils/helpers'\n\n\ntest('#runtimeError: should throw an error of type passed with message', t => {\n  t.throws(() => runtimeError(TypeError), TypeError)\n  t.throws(() => runtimeError(ReferenceError), ReferenceError)\n  t.throws(() => runtimeError(Error), Error)\n})\n"]}